# Basic site settings
title: "Rahul Shrivastava"
email: "your.email@example.com"
description: "Engineering Tech Lead specializing in distributed systems, cloud infrastructure, and AI/ML at scale."
baseurl: ""
url: "https://rhshriva.github.io"

# Social links
github_username: "rhshriva"
linkedin_username: "your_linkedin"

# Theme
remote_theme: "pages-themes/hacker@v0.2.0"

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Markdown processor
markdown: kramdown
highlighter: rouge

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

# SEO
author: "Rahul Shrivastava"
lang: "en-US"
