# Basic site settings
title: "Rahul Shrivastava"
description: "Engineering Tech Lead specializing in distributed systems, cloud infrastructure, and AI/ML at scale."
baseurl: ""
url: "https://rhshriva.github.io"

# Theme
theme: jekyll-theme-hacker

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/

# SEO
author: "Rahul Shrivastava"
lang: "en-US"
