# Site settings
title: Rahul Shrivastava
email: your.email@example.com
description: "Engineering Tech Lead specializing in distributed systems, cloud infrastructure, and AI/ML at scale. 20+ years of experience at AWS, Apple, Oracle, and Salesforce."
baseurl: ""
url: "https://rhshriva.github.io"
twitter_username: your_twitter
github_username: rhshriva
linkedin_username: your_linkedin

# Theme configuration
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Author info
author:
  name: "Rahul Shrivastava"
  email: "your.email@example.com"
  twitter: "your_twitter"

# Social media profiles
social:
  - platform: github
    user_url: "https://github.com/rhshriva"
  - platform: linkedin
    user_url: "https://linkedin.com/in/your_profile"
  - platform: email
    user_url: "mailto:your.email@example.com"

# Navigation (if using themes that support it)
navigation:
  - title: Home
    url: /
  - title: Projects
    url: /#featured-projects
  - title: Experience
    url: /#professional-experience
  - title: Contact
    url: /#lets-connect

# Custom variables for reuse
company_current: "GEICO Tech"
role_current: "Engineering Manager"
years_experience: "20+"
specialties: 
  - "Distributed Systems"
  - "Cloud Infrastructure" 
  - "AI/ML Systems"
  - "Performance Engineering"

# GitHub metadata
repository: "rhshriva/portfolio"
github:
  repository_url: "https://github.com/rhshriva/portfolio"
  owner_name: "rhshriva"
  owner_url: "https://github.com/rhshriva"

# Collections (for organizing content)
collections:
  projects:
    output: true
    permalink: /:collection/:name/
  certifications:
    output: false

# Default values
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"
      author: "Rahul Shrivastava"

# Customization for Hacker theme
hacker:
  date_format: "%b %-d, %Y"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Sass configuration for custom styling
sass:
  sass_dir: _sass
  style: compressed

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Analytics (optional)
# google_analytics: UA-XXXXXXXX-X # Replace with your tracking ID
# gtag: G-XXXXXXXXXX # Replace with your GA4 measurement ID
